/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "web-tracing",
  "description": "基于 JS / VUE 的 【埋点 & 性能采集 & 异常采集 & 请求采集 & 路由采集】 插件",
  "base": "/web-tracing-docu/",
  "headTags": [],
  "pages": [
    {
      "title": "设计核心(WWWWH)",
      "frontmatter": {},
      "regularPath": "/about/core.html",
      "relativePath": "about/core.md",
      "key": "v-6a8bc06c",
      "path": "/about/core.html",
      "headers": [
        {
          "level": 2,
          "title": "Who",
          "slug": "who"
        },
        {
          "level": 2,
          "title": "When",
          "slug": "when"
        },
        {
          "level": 2,
          "title": "Where",
          "slug": "where"
        },
        {
          "level": 2,
          "title": "What",
          "slug": "what"
        },
        {
          "level": 2,
          "title": "How",
          "slug": "how"
        }
      ]
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/about/introduce.html",
      "relativePath": "about/introduce.md",
      "key": "v-efb92280",
      "path": "/about/introduce.html",
      "headers": [
        {
          "level": 2,
          "title": "行为埋点",
          "slug": "行为埋点"
        },
        {
          "level": 2,
          "title": "性能采集",
          "slug": "性能采集"
        },
        {
          "level": 2,
          "title": "异常采集",
          "slug": "异常采集"
        },
        {
          "level": 2,
          "title": "请求采集",
          "slug": "请求采集"
        },
        {
          "level": 2,
          "title": "路由采集",
          "slug": "路由采集"
        }
      ]
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-fbeb95a4",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "行为埋点",
          "slug": "行为埋点"
        },
        {
          "level": 2,
          "title": "性能采集",
          "slug": "性能采集"
        },
        {
          "level": 2,
          "title": "异常采集",
          "slug": "异常采集"
        },
        {
          "level": 2,
          "title": "请求采集",
          "slug": "请求采集"
        },
        {
          "level": 2,
          "title": "路由采集",
          "slug": "路由采集"
        }
      ]
    },
    {
      "title": "勘误 & 补充",
      "frontmatter": {},
      "regularPath": "/about/warning.html",
      "relativePath": "about/warning.md",
      "key": "v-4a3b3d60",
      "path": "/about/warning.html",
      "headers": [
        {
          "level": 2,
          "title": "待做",
          "slug": "待做"
        },
        {
          "level": 2,
          "title": "微信",
          "slug": "微信"
        }
      ]
    },
    {
      "title": "err",
      "frontmatter": {},
      "regularPath": "/docs/err.html",
      "relativePath": "docs/err.md",
      "key": "v-f09c41b8",
      "path": "/docs/err.html",
      "headers": [
        {
          "level": 2,
          "title": "传给后台格式示例",
          "slug": "传给后台格式示例"
        },
        {
          "level": 3,
          "title": "Error实例引起的报错提交数据",
          "slug": "error实例引起的报错提交数据"
        },
        {
          "level": 3,
          "title": "不是Error实例引起的报错提交数据(这里是vue的报错)",
          "slug": "不是error实例引起的报错提交数据-这里是vue的报错"
        }
      ]
    },
    {
      "title": "示例",
      "frontmatter": {},
      "regularPath": "/demo/core.html",
      "relativePath": "demo/core.md",
      "key": "v-4386298c",
      "path": "/demo/core.html"
    },
    {
      "title": "基础说明",
      "frontmatter": {},
      "regularPath": "/docs/core.html",
      "relativePath": "docs/core.md",
      "key": "v-0e9dfa3a",
      "path": "/docs/core.html",
      "headers": [
        {
          "level": 2,
          "title": "插件采集规则",
          "slug": "插件采集规则"
        },
        {
          "level": 3,
          "title": "采集方式",
          "slug": "采集方式"
        },
        {
          "level": 3,
          "title": "发送后台地址配置",
          "slug": "发送后台地址配置"
        },
        {
          "level": 3,
          "title": "发送数据原理",
          "slug": "发送数据原理"
        },
        {
          "level": 3,
          "title": "发送间隔",
          "slug": "发送间隔"
        },
        {
          "level": 2,
          "title": "标识",
          "slug": "标识"
        }
      ]
    },
    {
      "title": "init",
      "frontmatter": {},
      "regularPath": "/docs/init.html",
      "relativePath": "docs/init.md",
      "key": "v-60ac9e9a",
      "path": "/docs/init.html",
      "headers": [
        {
          "level": 2,
          "title": "options",
          "slug": "options"
        },
        {
          "level": 2,
          "title": "示例",
          "slug": "示例"
        }
      ]
    },
    {
      "title": "http",
      "frontmatter": {},
      "regularPath": "/docs/http.html",
      "relativePath": "docs/http.md",
      "key": "v-05c9c8cc",
      "path": "/docs/http.html",
      "headers": [
        {
          "level": 2,
          "title": "传给后台格式示例",
          "slug": "传给后台格式示例"
        }
      ]
    },
    {
      "title": "event",
      "frontmatter": {},
      "regularPath": "/docs/event.html",
      "relativePath": "docs/event.md",
      "key": "v-6769a60c",
      "path": "/docs/event.html",
      "headers": [
        {
          "level": 2,
          "title": "页面卸载事件",
          "slug": "页面卸载事件"
        },
        {
          "level": 2,
          "title": "点击事件",
          "slug": "点击事件"
        },
        {
          "level": 3,
          "title": "eventId采集规则",
          "slug": "eventid采集规则"
        },
        {
          "level": 3,
          "title": "title采集规则",
          "slug": "title采集规则"
        },
        {
          "level": 3,
          "title": "params采集规则",
          "slug": "params采集规则"
        },
        {
          "level": 3,
          "title": "DOM元素标记",
          "slug": "dom元素标记"
        },
        {
          "level": 2,
          "title": "传给后台格式示例",
          "slug": "传给后台格式示例"
        },
        {
          "level": 3,
          "title": "示例一",
          "slug": "示例一"
        },
        {
          "level": 3,
          "title": "示例二",
          "slug": "示例二"
        }
      ]
    },
    {
      "title": "内置方法",
      "frontmatter": {},
      "regularPath": "/docs/methods.html",
      "relativePath": "docs/methods.md",
      "key": "v-78e9ff4a",
      "path": "/docs/methods.html",
      "headers": [
        {
          "level": 2,
          "title": "主动上报方法",
          "slug": "主动上报方法"
        },
        {
          "level": 3,
          "title": "traceError",
          "slug": "traceerror"
        },
        {
          "level": 3,
          "title": "tracePerformance",
          "slug": "traceperformance"
        },
        {
          "level": 3,
          "title": "traceCustomEvent",
          "slug": "tracecustomevent"
        },
        {
          "level": 3,
          "title": "tracePageView",
          "slug": "tracepageview"
        },
        {
          "level": 2,
          "title": "其他方法",
          "slug": "其他方法"
        }
      ]
    },
    {
      "title": "performance",
      "frontmatter": {},
      "regularPath": "/docs/performance.html",
      "relativePath": "docs/performance.md",
      "key": "v-b0301064",
      "path": "/docs/performance.html",
      "headers": [
        {
          "level": 2,
          "title": "数据来源",
          "slug": "数据来源"
        },
        {
          "level": 2,
          "title": "发送格式",
          "slug": "发送格式"
        },
        {
          "level": 3,
          "title": "首次页面性能数据对象格式",
          "slug": "首次页面性能数据对象格式"
        },
        {
          "level": 3,
          "title": "同步 & 异步资源加载时传给后台的对象格式(大部分依赖于performance.getEntriesByType('resource'))",
          "slug": "同步-异步资源加载时传给后台的对象格式-大部分依赖于performance-getentriesbytype-resource"
        },
        {
          "level": 2,
          "title": "传给后台格式示例",
          "slug": "传给后台格式示例"
        }
      ]
    },
    {
      "title": "pv",
      "frontmatter": {},
      "regularPath": "/docs/pv.html",
      "relativePath": "docs/pv.md",
      "key": "v-3628b35a",
      "path": "/docs/pv.html",
      "headers": [
        {
          "level": 2,
          "title": "action 字段解释",
          "slug": "action-字段解释"
        },
        {
          "level": 2,
          "title": "传给后台格式示例",
          "slug": "传给后台格式示例"
        }
      ]
    },
    {
      "title": "在 Vue 中使用",
      "frontmatter": {},
      "regularPath": "/use/vue.html",
      "relativePath": "use/vue.md",
      "key": "v-04731cc0",
      "path": "/use/vue.html",
      "headers": [
        {
          "level": 2,
          "title": "vue2引入 & 使用",
          "slug": "vue2引入-使用"
        },
        {
          "level": 2,
          "title": "vue3引入 & 使用",
          "slug": "vue3引入-使用"
        }
      ]
    },
    {
      "title": "数据结构",
      "frontmatter": {},
      "regularPath": "/docs/scheme.html",
      "relativePath": "docs/scheme.md",
      "key": "v-9f69bf8c",
      "path": "/docs/scheme.html",
      "headers": [
        {
          "level": 2,
          "title": "baseInfo",
          "slug": "baseinfo"
        },
        {
          "level": 2,
          "title": "eventInfo",
          "slug": "eventinfo"
        },
        {
          "level": 3,
          "title": "eventType",
          "slug": "eventtype"
        },
        {
          "level": 3,
          "title": "type",
          "slug": "type"
        },
        {
          "level": 3,
          "title": "eventId",
          "slug": "eventid"
        }
      ]
    },
    {
      "title": "待做",
      "frontmatter": {},
      "regularPath": "/todo/core.html",
      "relativePath": "todo/core.md",
      "key": "v-09d48c1a",
      "path": "/todo/core.html",
      "headers": [
        {
          "level": 2,
          "title": "API打点",
          "slug": "api打点"
        },
        {
          "level": 2,
          "title": "可配置",
          "slug": "可配置"
        },
        {
          "level": 2,
          "title": "设置全局参数",
          "slug": "设置全局参数"
        },
        {
          "level": 2,
          "title": "备注",
          "slug": "备注"
        },
        {
          "level": 2,
          "title": "params",
          "slug": "params"
        },
        {
          "level": 2,
          "title": "时间",
          "slug": "时间"
        },
        {
          "level": 2,
          "title": "error",
          "slug": "error"
        },
        {
          "level": 2,
          "title": "资源监控",
          "slug": "资源监控"
        },
        {
          "level": 2,
          "title": "请求",
          "slug": "请求"
        },
        {
          "level": 2,
          "title": "代码",
          "slug": "代码"
        }
      ]
    },
    {
      "title": "在 JS 中使用",
      "frontmatter": {},
      "regularPath": "/use/js.html",
      "relativePath": "use/js.md",
      "key": "v-431912aa",
      "path": "/use/js.html",
      "headers": [
        {
          "level": 2,
          "title": "方式一: 通过 script 标签引入",
          "slug": "方式一-通过-script-标签引入"
        },
        {
          "level": 2,
          "title": "方式二: 通过 import 引入",
          "slug": "方式二-通过-import-引入"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "subSidebar": "auto",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      }
    ],
    "sidebar": [
      {
        "title": "关于插件",
        "path": "/",
        "collapsable": false,
        "children": [
          {
            "title": "介绍",
            "path": "/"
          },
          {
            "title": "设计核心",
            "path": "/about/core"
          },
          {
            "title": "补充 & 勘误",
            "path": "/about/warning"
          }
        ]
      },
      {
        "title": "使用",
        "path": "/use/js",
        "collapsable": false,
        "children": [
          {
            "title": "在 JS 中使用",
            "path": "/use/js"
          },
          {
            "title": "在 Vue 中使用",
            "path": "/use/vue"
          }
        ]
      },
      {
        "title": "文档",
        "path": "/docs/core",
        "collapsable": false,
        "children": [
          {
            "title": "基础说明",
            "path": "/docs/core"
          },
          {
            "title": "数据结构",
            "path": "/docs/scheme"
          },
          {
            "title": "init 配置初始化",
            "path": "/docs/init"
          },
          {
            "title": "event 事件采集",
            "path": "/docs/event"
          },
          {
            "title": "pv 路由采集",
            "path": "/docs/pv"
          },
          {
            "title": "http 请求采集",
            "path": "/docs/http"
          },
          {
            "title": "err 错误采集",
            "path": "/docs/err"
          },
          {
            "title": "performance 资源采集",
            "path": "/docs/performance"
          },
          {
            "title": "methods 内置方法",
            "path": "/docs/methods"
          }
        ]
      },
      {
        "title": "示例",
        "path": "/demo/core"
      },
      {
        "title": "待做",
        "path": "/todo/core"
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}