/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "web-tracing",
  "description": "基于 JS / VUE 的 【埋点 & 性能采集 & 异常采集 & 请求采集 & 路由采集】 插件",
  "base": "/web-tracing-docu/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-fbeb95a4",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/demo/core.html",
      "relativePath": "demo/core.md",
      "key": "v-4386298c",
      "path": "/demo/core.html"
    },
    {
      "title": "web-tracing",
      "frontmatter": {},
      "regularPath": "/use/",
      "relativePath": "use/index.md",
      "key": "v-1f363d99",
      "path": "/use/",
      "headers": [
        {
          "level": 2,
          "title": "使用",
          "slug": "使用"
        },
        {
          "level": 3,
          "title": "init",
          "slug": "init"
        },
        {
          "level": 3,
          "title": "options",
          "slug": "options"
        },
        {
          "level": 3,
          "title": "页面元素标记",
          "slug": "页面元素标记"
        },
        {
          "level": 3,
          "title": "方法",
          "slug": "方法"
        },
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 3,
          "title": "设计核心(WWWWH)",
          "slug": "设计核心-wwwwh"
        },
        {
          "level": 3,
          "title": "埋点自动分类采集",
          "slug": "埋点自动分类采集"
        },
        {
          "level": 3,
          "title": "事件数据结构",
          "slug": "事件数据结构"
        }
      ]
    },
    {
      "title": "我是标题",
      "frontmatter": {},
      "regularPath": "/use/js.html",
      "relativePath": "use/js.md",
      "key": "v-431912aa",
      "path": "/use/js.html",
      "headers": [
        {
          "level": 2,
          "title": "阿达十大的12",
          "slug": "阿达十大的12"
        },
        {
          "level": 2,
          "title": "阿达十大的123",
          "slug": "阿达十大的123"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/docu/core.html",
      "relativePath": "docu/core.md",
      "key": "v-306a7d7a",
      "path": "/docu/core.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/use/vue.html",
      "relativePath": "use/vue.md",
      "key": "v-04731cc0",
      "path": "/use/vue.html"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "subSidebar": "auto",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      }
    ],
    "sidebar": [
      {
        "title": "关于插件",
        "path": "/",
        "collapsable": false,
        "children": [
          {
            "title": "介绍",
            "path": "/"
          }
        ]
      },
      {
        "title": "使用",
        "path": "/use/js",
        "collapsable": false,
        "children": [
          {
            "title": "在 JS 中使用",
            "path": "/use/js"
          },
          {
            "title": "在 Vue 中使用",
            "path": "/use/vue"
          }
        ]
      },
      {
        "title": "文档",
        "path": "/docu/core"
      },
      {
        "title": "示例",
        "path": "/demo/core"
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}