/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "web-tracing",
  "description": "前端 - 埋点, 性能采集, 异常采集, 请求采集, 路由采集",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-7ea69fa8",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/handbook/Geners.html",
      "relativePath": "handbook/Geners.md",
      "key": "v-6dd5e47c",
      "path": "/handbook/Geners.html"
    },
    {
      "title": "我是标题",
      "frontmatter": {
        "title": "我是标题",
        "author": "三季",
        "date": "2022-1-5"
      },
      "regularPath": "/handbook/Geners_2.html",
      "relativePath": "handbook/Geners_2.md",
      "key": "v-cb998748",
      "path": "/handbook/Geners_2.html",
      "headers": [
        {
          "level": 2,
          "title": "阿达十大的12",
          "slug": "阿达十大的12"
        },
        {
          "level": 2,
          "title": "阿达十大的123",
          "slug": "阿达十大的123"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "博客地址",
        "items": [
          {
            "text": "Github",
            "link": "https://github.com/mqyqingfeng"
          },
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/712139234359182/posts"
          }
        ]
      }
    ],
    "sidebar": [
      {
        "title": "欢迎学习",
        "path": "/",
        "collapsable": false,
        "children": [
          {
            "title": "学前必读",
            "path": "/"
          }
        ]
      },
      {
        "title": "基础学习",
        "path": "/handbook/Geners",
        "collapsable": false,
        "children": [
          {
            "title": "条件类型",
            "path": "/handbook/Geners"
          },
          {
            "title": "泛型",
            "path": "/handbook/Geners_2"
          }
        ]
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}